version: '3.8'

services:
  # Auth Service Database
  auth-service-db:
    image: postgres:latest
    container_name: auth-service-db
    environment:
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - auth-service-db-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  # Patient Service Database
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    environment:
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5433:5432"  # Changed to avoid port conflict with auth-service-db
    volumes:
      - patient-service-db-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  # Kafka Service
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
    ports:
      - "9092:9092"
      - "9094:9094"
    networks:
      - app-network
    restart: unless-stopped

volumes:
  auth-service-db-data:
  patient-service-db-data:

networks:
  app-network:
    driver: bridge